export const GET_POKEMONS_REQUEST = 'GET_POKEMONS_REQUEST';
export const GET_POKEMONS_SUCCESS = 'GET_POKEMONS_SUCCESS';
export const GET_POKEMONS_ERROR = 'GET_POKEMONS_ERROR';
export const GET_POKEMONS_RESET = 'GET_POKEMONS_RESET';

export const SET_GENERATION = 'SET_GENERATION';

export const GET_POKEMON_INFO_REQUEST = 'GET_POKEMON_INFO_REQUEST';
export const GET_POKEMON_INFO_SUCCESS = 'GET_POKEMON_INFO_SUCCESS';
export const GET_POKEMON_INFO_ERROR = 'GET_POKEMON_INFO_ERROR';
export const GET_POKEMON_INFO_RESET = 'GET_POKEMON_INFO_RESET';
